// SPDX-License-Identifier: MIT
pragma solidity 0.8.30;

import {Pausable} from "@openzeppelin/contracts/utils/Pausable.sol";

import {ICustodialNFTVault} from "../../src/interfaces/ICustodialNFTVault.sol";
import {VaultTestBase} from "../utils/VaultTestBase.sol";

/// @dev Property tests for limit validation and role-array canonicalization.
contract ConfigurationFuzzTest is VaultTestBase {
    function testFuzz_setLimitsAcceptedIffWithinHardCapsAndSamePeriod(
        uint16 maxTokens,
        uint32 period,
        uint8 maxItems
    ) public {
        bool withinCaps = maxTokens >= 1 && maxTokens <= 2000 && period >= 1 && period <= 2_592_000
            && maxItems >= 1 && maxItems <= 50;
        bool samePeriod = period == DEFAULT_PERIOD;

        vm.prank(admin);
        if (withinCaps && samePeriod) {
            vault.setLimits(ICustodialNFTVault.Limits(maxTokens, period, maxItems));
            ICustodialNFTVault.Limits memory stored = vault.getLimits();
            assertEq(stored.maxTokens, maxTokens);
            assertEq(stored.periodSeconds, period);
            assertEq(stored.maxItemsPerBatch, maxItems);
        } else if (withinCaps) {
            vm.expectRevert(ICustodialNFTVault.PeriodIsImmutable.selector);
            vault.setLimits(ICustodialNFTVault.Limits(maxTokens, period, maxItems));
        } else {
            vm.expectRevert(ICustodialNFTVault.InvalidLimits.selector);
            vault.setLimits(ICustodialNFTVault.Limits(maxTokens, period, maxItems));
        }
    }

    function testFuzz_epochResetAcceptedIffPausedAndWithinCaps(uint32 period, bool paused_) public {
        if (paused_) {
            vm.prank(locker1);
            vault.lock();
        }
        bool withinCaps = period >= 1 && period <= 2_592_000;

        vm.prank(admin);
        if (!paused_) {
            vm.expectRevert(Pausable.ExpectedPause.selector);
            vault.resetWindowAndSetPeriod(period);
        } else if (!withinCaps) {
            vm.expectRevert(ICustodialNFTVault.InvalidLimits.selector);
            vault.resetWindowAndSetPeriod(period);
        } else {
            vault.resetWindowAndSetPeriod(period);
            assertEq(vault.getLimits().periodSeconds, period);
            assertEq(vault.getRecentWithdrawn(), 0);
            assertTrue(vault.isLocked(), "epoch reset never unpauses");
        }
    }

    function testFuzz_setLimitsPreservesHistory(uint16 maxTokens, uint8 maxItems) public {
        maxTokens = uint16(bound(maxTokens, 1, 2000));
        maxItems = uint8(bound(maxItems, 1, 50));
        assertTrue(_withdrawAs(manager1, _batch721(0, 10)));

        vm.prank(admin);
        vault.setLimits(ICustodialNFTVault.Limits(maxTokens, DEFAULT_PERIOD, maxItems));
        assertEq(_used(), 10, "limit changes never reset active history");
    }

    function testFuzz_canonicalRoleArraysAccepted(uint160 start, uint256 count, uint256 gapSeed)
        public
    {
        count = bound(count, 1, 10);
        start = uint160(bound(start, 1, type(uint160).max - 10 * 1000));

        address[] memory arr = new address[](count);
        uint160 cursor = start;
        for (uint256 i; i < count; ++i) {
            cursor += uint160(1 + uint256(keccak256(abi.encode(gapSeed, i))) % 997);
            arr[i] = address(cursor);
        }

        vm.prank(admin);
        vault.setManagers(arr);

        address[] memory stored = vault.getManagers();
        assertEq(stored.length, count);
        for (uint256 i; i < count; ++i) {
            assertEq(stored[i], arr[i]);
            assertTrue(vault.isManager(arr[i]));
        }
        // Old managers were revoked (unless regenerated by chance).
        if (!_contains(arr, manager1)) assertFalse(vault.isManager(manager1));
        if (!_contains(arr, manager2)) assertFalse(vault.isManager(manager2));
    }

    function testFuzz_nonCanonicalRoleArraysRevert(uint256 count, uint256 breakAt) public {
        count = bound(count, 2, 10);
        breakAt = bound(breakAt, 1, count - 1);

        address[] memory arr = new address[](count);
        for (uint256 i; i < count; ++i) {
            // Bounded synthetic addresses; the cast cannot truncate.
            // forge-lint: disable-next-line(unsafe-typecast)
            arr[i] = address(uint160(0x1000 + i * 10));
        }
        // Introduce an order violation (duplicate) at breakAt.
        arr[breakAt] = arr[breakAt - 1];

        vm.expectRevert(ICustodialNFTVault.RoleAddressesNotSorted.selector);
        vm.prank(admin);
        vault.setManagers(arr);

        // The previous manager set must remain intact.
        assertTrue(vault.isManager(manager1));
        assertTrue(vault.isManager(manager2));
    }

    function _contains(address[] memory arr, address a) private pure returns (bool) {
        for (uint256 i; i < arr.length; ++i) {
            if (arr[i] == a) return true;
        }
        return false;
    }
}
